name: CI Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Code & Infrastructure Analysis
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Lint shell scripts with Shellcheck
        run: |
          if [ -n "$(find . -type f -name '*.sh')" ]; then
            find . -type f -name "*.sh" -exec shellcheck {} +
          else
            echo "No shell scripts found to lint."
          fi

      - name: Run Tests & Coverage
        run: npm run test

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/

  build:
    name: Build and Push Docker Image
    needs: lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,format=long
            type=raw,value=stable,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=ref,event=tag
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy to Target Node
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute deployment script via SSH
        run: |
          scp -o StrictHostKeyChecking=no mywebapp.service deploy.sh edward@192.168.50.96:/tmp/
          
          ssh -o StrictHostKeyChecking=no edward@192.168.50.96 "cd /tmp && chmod +x deploy.sh && ./deploy.sh"
